version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"